import type { Board, PinPlanExportFormat } from "@/lib/boards";
import { revisionNotesFor } from "@/lib/board-utilities";
import type { PlanAssignment } from "@/lib/pin-planner";
import { verificationSourceFor } from "@/lib/source-trust";

// Exports a pin plan as code. Pure: the caller supplies the date so output is
// reproducible. Each format is offered only when the board's pin data names
// pins the way that toolchain does (`pinFunctions.exports`), and every file
// opens with the board, connector, revision notes, verification source, and a
// reminder to verify before wiring.

export type PlanExport = {
  format: PinPlanExportFormat;
  label: string;
  filename: string;
  mimeType: string;
  text: string;
};

const formatInfo: Record<PinPlanExportFormat, { label: string; suffix: string; mimeType: string }> = {
  "c-header": { label: "C header", suffix: ".h", mimeType: "text/x-c" },
  micropython: { label: "MicroPython", suffix: "-micropython.py", mimeType: "text/x-python" },
  arduino: { label: "Arduino", suffix: "-arduino.h", mimeType: "text/x-c" },
  json: { label: "JSON", suffix: ".json", mimeType: "application/json" },
};

export const planNotice = "Generated by PinHub — verify against the source before wiring.";

// Controls and line/paragraph separators would end a comment line early and
// turn the rest of a catalog string into code.
const lineBreaking = /[\u0000-\u001f\u007f-\u009f\u2028\u2029]+/g;

function oneLine(value: string): string {
  return value.replace(lineBreaking, " ").replace(/\s+/g, " ").trim();
}

function identifier(value: string): string {
  return value.toUpperCase().replace(/[^A-Z0-9]+/g, "_").replace(/^_+|_+$/g, "");
}

function variable(value: string): string {
  const name = value.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
  return /^[a-z_]/.test(name) ? name : `p_${name}`;
}

/** `pinhub-plan-<board id><suffix>`, using only [a-z0-9-] before the suffix. */
export function planFilename(board: Pick<Board, "id">, format: PinPlanExportFormat): string {
  const id = board.id.toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, "");
  return `pinhub-plan-${id || "board"}${formatInfo[format].suffix}`;
}

function headerLines(board: Board, date: string): string[] {
  const revisions = revisionNotesFor(board).map(oneLine);
  const source = verificationSourceFor(board);
  const lines = [
    `PinHub pin plan: ${oneLine(board.name)} (${board.id})`,
    `Connector: ${oneLine(board.pinout?.connector ?? "not recorded")}`,
    ...(revisions.length
      ? revisions.map((note) => `Revision note: ${note}`)
      : ["Revision notes: none recorded in PinHub; check your board's silkscreen revision."]),
    `Verify against: ${source ? `${oneLine(source.label)} ${source.url}` : "the board's documentation"}`,
    ...(board.pinFunctions?.sources ?? []).map((item) => `Pin functions from: ${item.url}`),
  ];
  if (board.pinFunctions?.mux.model === "matrix") {
    lines.push(`Pin routing: ${oneLine(board.pinFunctions.mux.note)}`);
  }
  lines.push(`${planNotice} ${date}`);
  return lines;
}

function pinDescription(item: PlanAssignment): string {
  // Grouped maps number pins within each group, and not always as physical
  // pin numbers (the UNO map counts along its headers), so say "position".
  const place = item.group
    ? `${oneLine(item.group)} position ${item.pin.position}`
    : `physical pin ${item.pin.position}`;
  return `${place}, ${oneLine(item.pin.label)}${item.routed ? ", routed through the GPIO matrix" : ""}`;
}

function cautionLines(item: PlanAssignment): string[] {
  return item.cautions.map(
    (caution) => `CAUTION (${item.pin.mcu?.name ?? item.pin.label}, ${caution.flag}): ${oneLine(caution.note)}`,
  );
}

function channelNumber(signal: string): number | null {
  const match = /^CH(\d+)$/.exec(signal);
  return match ? Number(match[1]) : null;
}

function unitName(item: PlanAssignment): string {
  return item.peripheral === "GPIO" || item.peripheral === "PWM" || item.peripheral === "ADC" || item.peripheral === "DAC"
    ? `${item.peripheral}${item.unit}`
    : `${item.instance}_${item.signal}`;
}

function cHeader(board: Board, assignments: PlanAssignment[], date: string): string {
  const guard = `PINHUB_PLAN_${identifier(board.id)}_H`;
  const avr = assignments.every((item) => item.pin.mcu?.gpio === undefined);
  const lines = headerLines(board, date).map((line) => `// ${line}`);
  lines.push("", `#ifndef ${guard}`, `#define ${guard}`, "");
  if (avr) lines.push("#include <avr/io.h>", "");
  for (const item of assignments) {
    const mcu = item.pin.mcu!;
    const name = `PINHUB_${identifier(unitName(item))}`;
    const what = [item.instance, item.signal !== "IO" ? item.signal : ""].filter(Boolean).join(" ");
    lines.push(...cautionLines(item).map((line) => `// ${line}`));
    lines.push(`// ${item.peripheral} ${item.unit}${what ? `: ${what}` : ""} on ${pinDescription(item)}`);
    const port = /^P([A-Z])([0-7])$/.exec(mcu.name);
    if (mcu.gpio !== undefined) {
      lines.push(`#define ${name} ${mcu.gpio}`);
    } else if (port) {
      lines.push(
        `#define ${name}_PORT PORT${port[1]}`,
        `#define ${name}_DDR DDR${port[1]}`,
        `#define ${name}_PIN PIN${port[1]}`,
        `#define ${name}_BIT ${mcu.name}`,
      );
    }
    const channel =
      item.peripheral === "ADC" || item.peripheral === "DAC" ? channelNumber(item.signal) : null;
    if (channel !== null) lines.push(`#define ${name}_CHANNEL ${channel}`);
  }
  lines.push("", `#endif // ${guard}`, "");
  return lines.join("\n");
}

function microPython(board: Board, assignments: PlanAssignment[], date: string): string {
  const busIds = board.pinFunctions?.micropythonBusIds ?? {};
  const pinOf = (item: PlanAssignment) => `Pin(${item.pin.mcu!.gpio})`;
  const classes = new Set<string>(["Pin"]);
  const body: string[] = [];
  const units = new Map<string, PlanAssignment[]>();
  for (const item of assignments) {
    const key = `${item.peripheral}:${item.unit}`;
    units.set(key, [...(units.get(key) ?? []), item]);
  }
  for (const items of units.values()) {
    const [first] = items;
    const signal = (name: string) => items.find((item) => item.signal.replace(/^CS\d+$/, "CS") === name)!;
    body.push(...items.flatMap(cautionLines).map((line) => `# ${line}`));
    const comment = `  # ${first.peripheral} ${first.unit}: ${items.map(pinDescription).join("; ")}`;
    if (first.peripheral === "I2C" || first.peripheral === "SPI" || first.peripheral === "UART") {
      const id = first.instance ? busIds[first.instance] : undefined;
      const name = variable(first.instance ?? `${first.peripheral}${first.unit}`);
      if (id === undefined) {
        body.push(`# ${first.instance}: no MicroPython bus id is recorded for this board.`);
        continue;
      }
      classes.add(first.peripheral);
      if (first.peripheral === "I2C") {
        body.push(`${name} = I2C(${id}, sda=${pinOf(signal("SDA"))}, scl=${pinOf(signal("SCL"))})${comment}`);
      } else if (first.peripheral === "SPI") {
        body.push(
          `${name} = SPI(${id}, sck=${pinOf(signal("SCK"))}, mosi=${pinOf(signal("MOSI"))}, miso=${pinOf(signal("MISO"))})${comment}`,
          `${name}_cs = Pin(${signal("CS").pin.mcu!.gpio}, Pin.OUT, value=1)`,
        );
      } else {
        body.push(`${name} = UART(${id}, tx=${pinOf(signal("TX"))}, rx=${pinOf(signal("RX"))})${comment}`);
      }
    } else if (first.peripheral === "PWM" || first.peripheral === "ADC" || first.peripheral === "DAC") {
      classes.add(first.peripheral);
      body.push(`${variable(unitName(first))} = ${first.peripheral}(${pinOf(first)})${comment} (${first.instance} ${first.signal})`);
    } else {
      body.push(`${variable(unitName(first))} = ${pinOf(first)}${comment}`);
    }
  }
  return [
    ...headerLines(board, date).map((line) => `# ${line}`),
    "",
    `from machine import ${[...classes].sort().join(", ")}`,
    "",
    ...body,
    "",
  ].join("\n");
}

function arduino(board: Board, assignments: PlanAssignment[], date: string): string {
  const lines = headerLines(board, date).map((line) => `// ${line}`);
  lines.push("", "#pragma once", "#include <Arduino.h>", "");
  for (const item of assignments) {
    lines.push(...cautionLines(item).map((line) => `// ${line}`));
    const what = [item.instance, item.signal !== "IO" ? item.signal : ""].filter(Boolean).join(" ");
    lines.push(
      `const uint8_t PINHUB_${identifier(unitName(item))} = ${item.pin.mcu!.arduino};  // ${item.peripheral} ${item.unit}${what ? `: ${what}` : ""} on ${pinDescription(item)}`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

function json(board: Board, assignments: PlanAssignment[], date: string): string {
  const source = verificationSourceFor(board);
  return `${JSON.stringify(
    {
      board: { id: board.id, name: board.name },
      connector: board.pinout?.connector ?? null,
      revisionNotes: revisionNotesFor(board),
      verifySource: source ? { label: source.label, url: source.url } : null,
      notice: planNotice,
      generated: date,
      pinFunctionSources: (board.pinFunctions?.sources ?? []).map((item) => item.url),
      mux: board.pinFunctions
        ? { model: board.pinFunctions.mux.model, note: board.pinFunctions.mux.note }
        : null,
      assignments: assignments.map((item) => ({
        peripheral: item.peripheral,
        unit: item.unit,
        ...(item.instance ? { instance: item.instance } : {}),
        signal: item.signal,
        pin: {
          position: item.pin.position,
          label: item.pin.label,
          ...(item.group ? { group: item.group } : {}),
        },
        mcu: item.pin.mcu,
        routed: item.routed,
        default: item.isDefault,
        cautions: item.cautions,
      })),
    },
    null,
    2,
  )}\n`;
}

const builders: Record<PinPlanExportFormat, (board: Board, assignments: PlanAssignment[], date: string) => string> = {
  "c-header": cHeader,
  micropython: microPython,
  arduino,
  json,
};

/** Whether every assigned pin carries the naming `format` needs. */
function supports(format: PinPlanExportFormat, assignments: PlanAssignment[]): boolean {
  return assignments.every((item) => {
    const mcu = item.pin.mcu;
    if (!mcu) return false;
    if (format === "micropython") return mcu.gpio !== undefined;
    if (format === "arduino") return Boolean(mcu.arduino);
    if (format === "c-header") return mcu.gpio !== undefined || /^P[A-Z][0-7]$/.test(mcu.name);
    return true;
  });
}

/**
 * The exports this board's data supports for a plan, in the board's order.
 * `date` is an ISO calendar date (YYYY-MM-DD) stamped into each file.
 */
export function planExports(board: Board, assignments: PlanAssignment[], date: string): PlanExport[] {
  if (!board.pinFunctions || !assignments.length) return [];
  const stamp = /^\d{4}-\d{2}-\d{2}$/.test(date) ? date : "";
  return board.pinFunctions.exports
    .filter((format) => supports(format, assignments))
    .map((format) => ({
      format,
      label: formatInfo[format].label,
      filename: planFilename(board, format),
      mimeType: formatInfo[format].mimeType,
      text: builders[format](board, assignments, stamp),
    }));
}
