import { expect, test, type Locator, type Page } from "@playwright/test";
import { expectColor } from "./color";

async function planner(page: Page): Promise<Locator> {
  const section = page.getByRole("region", { name: "Pin planner" });
  await expect(section).toBeVisible();
  return section;
}

/** Taps a stepper until its count reads `target`, surviving a cold hydration. */
async function setCount(section: Locator, peripheral: string, target: number) {
  const count = section.locator(`[data-plan-count="${peripheral}"]`);
  const add = section.getByRole("button", { name: `Add one ${peripheral}`, exact: true });
  await expect(async () => {
    const current = Number(await count.textContent());
    if (current < target) await add.click();
    await expect(count).toHaveText(String(target), { timeout: 1000 });
  }).toPass();
}

test.describe("pin planner", () => {
  test("a phone reaches the planner from the catalog panel", async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto("/");
    await page.getByRole("button", { name: "Show Raspberry Pi Pico details", exact: true }).click();
    const panel = page.getByRole("complementary").filter({
      has: page.getByRole("heading", { name: "Raspberry Pi Pico", exact: true }),
    });
    const open = panel.getByRole("link", { name: /Open full board page/ });
    await expect(open).toContainText("Plan pins for your circuit");
    const box = await open.boundingBox();
    expect(box?.height).toBeGreaterThanOrEqual(44);

    await open.click();
    await expect(page).toHaveURL(/\/boards\/raspberry-pi-pico#plan$/);
    await expect(await planner(page)).toBeInViewport();
  });

  test("builds a Pico plan, shares it by URL, highlights it, and exports it", async ({ page, context }) => {
    await context.grantPermissions(["clipboard-read", "clipboard-write"]);
    const errors: string[] = [];
    page.on("pageerror", (error) => errors.push(error.message));
    await page.goto("/boards/raspberry-pi-pico");
    let section = await planner(page);

    await setCount(section, "I2C", 1);
    await setCount(section, "SPI", 1);
    await setCount(section, "PWM", 2);
    await setCount(section, "ADC", 1);
    await setCount(section, "GPIO", 2);
    const status = section.locator("[data-plan-status]");
    await expect(status).toHaveText("Plan ready: 11 pins assigned.");
    await expect(page).toHaveURL(/\?plan=i2c1\.spi1\.pwm2\.adc1\.gpio2$/);

    // The shared link reproduces the plan on a fresh load.
    await page.goto(page.url());
    section = await planner(page);
    await expect(section.getByRole("group", { name: "I2C, 1 planned, up to 2" })).toBeVisible();
    await expect(section.locator('[data-plan-count="GPIO"]')).toHaveText("2");
    await expect(section.locator("[data-plan-status]")).toHaveText("Plan ready: 11 pins assigned.");

    // Every assigned pin is ringed on the planner's drawing, in a role hue.
    const rings = section.locator(".bv-planned-ring");
    await expect(rings).toHaveCount(11);
    for (const stroke of await rings.evaluateAll((nodes) => nodes.map((node) => node.getAttribute("stroke")))) {
      expect(stroke?.toLowerCase()).not.toBe("#22d3ee");
    }

    // A result row probes its pin on the drawing.
    const row = section.getByRole("button", { name: "Show pin 6, GP4 on the board" });
    await row.click();
    await expect(row).toHaveAttribute("aria-pressed", "true");
    await expect(section.getByRole("button", { name: /^Pin 6, GP4/ })).toHaveAttribute("aria-pressed", "true");

    // Exports carry the plan and the verification header.
    const preview = section.getByLabel(/export preview$/);
    await expect(preview).toContainText("#define PINHUB_I2C0_SDA 4");
    await expect(preview).toContainText("Generated by PinHub — verify against the source before wiring.");
    await section.getByRole("button", { name: "MicroPython", exact: true }).click();
    await expect(preview).toContainText("i2c0 = I2C(0, sda=Pin(4), scl=Pin(5))");
    await section.getByRole("button", { name: "Copy", exact: true }).click();
    await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toContain("from machine import");
    await expect(section.getByRole("link", { name: "Download" })).toHaveAttribute(
      "download",
      "pinhub-plan-raspberry-pi-pico-micropython.py",
    );
    expect(errors).toEqual([]);
  });

  test("explains an unsatisfiable plan in orange, in both themes", async ({ page }) => {
    await page.goto("/boards/arduino-uno-rev3?plan=spi1.pwm6");
    const section = await planner(page);
    const status = section.locator("[data-plan-status]");
    await expect(status).toHaveText("No plan fits. 6× PWM doesn't fit alongside 1× SPI: they need the same pins.");
    for (const [theme, color] of [
      ["dark", "lab(94.7127 3.58391 14.3151)"],
      ["light", "rgb(154, 52, 18)"],
    ] as const) {
      await page.locator("html").evaluate((element, value) => element.setAttribute("data-theme", value), theme);
      await expectColor(status, color);
    }
  });

  test("the full pinout view carries the planner too", async ({ page }) => {
    await page.goto("/pinout/esp32-devkitc?plan=i2c1.gpio1");
    const section = await planner(page);
    await expect(section.locator("[data-plan-status]")).toHaveText("Plan ready: 3 pins assigned.");
    await expect(section).toContainText("GPIO matrix");
  });

  test("a board without pin function data says so and offers a report", async ({ page }) => {
    await page.goto("/boards/raspberry-pi-4-model-b?plan=i2c1");
    const section = await planner(page);
    await expect(section).toContainText("Pin planning isn't available for this board yet.");
    const report = section.getByRole("link", { name: /Report a data error/ });
    const href = new URL((await report.getAttribute("href")) ?? "");
    expect(href.searchParams.get("board")).toBe("raspberry-pi-4-model-b");
    await expect(report).toHaveAttribute("rel", "noopener noreferrer");
    await expect(section.getByRole("button", { name: /^Add one/ })).toHaveCount(0);
  });
});
