/**
 * Hand-curated short aliases for generated boards — the names people actually
 * type. Keys are site board ids. Aliases must be normalized (lowercase,
 * hyphen-separated) and unique across the whole catalog; the catalog test
 * suite enforces both.
 */
export const curatedAliases: Record<string, string[]> = {
  "raspberry-pi-4-model-b": ["rpi4", "pi4", "raspberry-pi-4"],
  "raspberry-pi-3-model-b-plus": ["rpi3", "pi3", "raspberry-pi-3"],
  "raspberry-pi-zero-2-w": ["pi-zero-2-w", "zero-2-w", "pi-zero-2"],
  "raspberry-pi-pico-2": ["pico2", "pico-2"],
  "raspberry-pi-pico-2-w": ["pico2w", "pico-2-w"],
  "raspberry-pi-500": ["pi500", "rpi500"],
  "arduino-uno-r4-wifi": ["uno-r4-wifi", "r4-wifi"],
  "arduino-uno-r4-minima": ["uno-r4-minima", "r4-minima"],
  "arduino-nano": ["nano"],
  "arduino-mega-2560-rev3": ["mega", "mega2560", "arduino-mega"],
  "arduino-nano-esp32": ["nano-esp32"],
  "arduino-nano-33-ble-sense": ["nano-33-ble", "nano-33"],
  "arduino-mkr-wifi-1010": ["mkr-wifi", "mkr1010"],
  "esp32-devkitc": ["devkitc", "esp32-devkitc-v4"],
  "esp32-s3-devkitc-1": ["esp32-s3", "s3-devkitc"],
  "esp32-c3-devkitm-1": ["esp32-c3"],
  "esp32-c6-devkitc-1": ["esp32-c6"],
  "esp32-h2-devkitm-1": ["esp32-h2"],
  "esp32-s2-saola-1": ["esp32-s2", "saola"],
  "nodemcu-devkit-v1": ["nodemcu", "esp8266"],
  "lolin-d1-mini": ["d1-mini", "wemos-d1-mini"],
  "lolin-s2-mini": ["s2-mini"],
  "stm32f103-blue-pill": ["blue-pill", "bluepill"],
  "weact-black-pill-stm32f411": ["black-pill", "blackpill"],
  "stm32-nucleo-f401re": ["nucleo", "nucleo-f401re"],
  "beaglebone-black": ["bbb", "beaglebone"],
  "teensy-41": ["teensy", "teensy41"],
  "bbc-microbit-v2": ["microbit", "micro-bit"],
  "jetson-orin-nano-dev-kit": ["jetson", "orin-nano"],
  "seeed-xiao-rp2040": ["xiao-rp2040"],
  "seeed-xiao-esp32s3": ["xiao-esp32s3"],
  "orange-pi-5": ["opi5"],
  "milkv-duo": ["milkv"],
  "particle-photon-2": ["photon", "photon-2"],
  "seeed-wio-terminal": ["wio"],
  "adafruit-feather-rp2040": ["feather-rp2040"],
  "pine64-rockpro64": ["rockpro64"],
  "libre-computer-le-potato": ["le-potato", "potato"],
  "nxp-frdm-kl25z": ["frdm-kl25z", "kl25z"],
  "digilent-nexys-a7-100t": ["nexys-a7", "nexys-a7-100t", "nexys"],
  "terasic-de10-lite": ["de10-lite", "de10lite"],
  "starfive-visionfive-2": ["visionfive2", "visionfive-2", "vf2"],
  "flipper-zero": ["flipper", "flipperzero"],
  "esp32-p4-function-ev-board": ["esp32-p4", "p4-function-ev"],
  "radxa-rock-3a": ["rock-3a", "rock3a"],
};
